<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="42.0850" tests="6" failures="2">
  <testsuite name="Root Suite" timestamp="2022-01-13T06:43:58" tests="0" file="cypress/integration/code/codeDamnTest.js" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Basic tests" timestamp="2022-01-13T06:43:58" tests="6" time="42.0650" failures="2">
    <testcase name="Basic tests We have correct page title" time="0.0000" classname="We have correct page title">
      <failure message="The following error originated from your application code, not from Cypress.

  &gt; Script error.

Cypress detected that an uncaught error was thrown from a cross origin script.

We cannot provide you the stack trace, line number, or file where this error occurred.

Check your Developer Tools Console for the actual error - it should be printed there.

It&apos;s possible to enable debugging these scripts by adding the `crossorigin` attribute and setting a CORS header.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application

https://on.cypress.io/cross-origin-script-error" type="Error"><![CDATA[Error: The following error originated from your application code, not from Cypress.

  > Script error.

Cypress detected that an uncaught error was thrown from a cross origin script.

We cannot provide you the stack trace, line number, or file where this error occurred.

Check your Developer Tools Console for the actual error - it should be printed there.

It's possible to enable debugging these scripts by adding the `crossorigin` attribute and setting a CORS header.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application

https://on.cypress.io/cross-origin-script-error
]]></failure>
    </testcase>
    <testcase name="Basic tests We have correct gotquestions page title" time="6.3980" classname="We have correct gotquestions page title">
    </testcase>
    <testcase name="Basic tests We have correct gotquestions page title" time="0.0000" classname="We have correct gotquestions page title">
      <failure message="Timed out retrying after 4000ms: Expected to find content: &apos;Who is Saint Nicholas?&apos; but never did." type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 4000ms: Expected to find content: 'Who is Saint Nicholas?' but never did.
    at Context.eval (https://www.gotquestions.org/__cypress/tests?p=cypress\integration\code\codeDamnTest.js:111:8)]]></failure>
    </testcase>
    <testcase name="Basic tests We have correct software testing page title" time="6.5960" classname="We have correct software testing page title">
    </testcase>
    <testcase name="Basic tests We have correct software testing CASE STUDY" time="4.6430" classname="We have correct software testing CASE STUDY">
    </testcase>
    <testcase name="Basic tests We have correct software testing WORKSHOP" time="4.3370" classname="We have correct software testing WORKSHOP">
    </testcase>
  </testsuite>
</testsuites>