<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.8690" tests="4" failures="4">
  <testsuite name="Root Suite" timestamp="2022-01-13T06:45:50" tests="0" file="cypress/integration/code/sampleAuth.js" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Logging In - Basic Auth" timestamp="2022-01-13T06:45:50" tests="0" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="cy.request" timestamp="2022-01-13T06:45:50" tests="3" time="0.6240" failures="3">
    <testcase name="Logging In - Basic Auth cy.request without authorization gets 401" time="0.0000" classname="without authorization gets 401">
      <failure message="`cy.request()` must be provided a fully qualified `url` - one that begins with `http`. By default `cy.request()` will use either the current window&apos;s origin or the `baseUrl` in `cypress.json`. Neither of those values were present.

https://on.cypress.io/request" type="CypressError"><![CDATA[CypressError: `cy.request()` must be provided a fully qualified `url` - one that begins with `http`. By default `cy.request()` will use either the current window's origin or the `baseUrl` in `cypress.json`. Neither of those values were present.

https://on.cypress.io/request
    at Context.request (http://localhost:52036/__cypress/runner/cypress_runner.js:159202:78)
From Your Spec Code:
    at Context.eval (http://localhost:52036/__cypress/tests?p=cypress\integration\code\sampleAuth.js:107:10)]]></failure>
    </testcase>
    <testcase name="Logging In - Basic Auth cy.request with authorization" time="0.0000" classname="with authorization">
      <failure message="`cy.request()` must be provided a fully qualified `url` - one that begins with `http`. By default `cy.request()` will use either the current window&apos;s origin or the `baseUrl` in `cypress.json`. Neither of those values were present.

https://on.cypress.io/request" type="CypressError"><![CDATA[CypressError: `cy.request()` must be provided a fully qualified `url` - one that begins with `http`. By default `cy.request()` will use either the current window's origin or the `baseUrl` in `cypress.json`. Neither of those values were present.

https://on.cypress.io/request
    at Context.request (http://localhost:52036/__cypress/runner/cypress_runner.js:159202:78)
From Your Spec Code:
    at Context.eval (http://localhost:52036/__cypress/tests?p=cypress\integration\code\sampleAuth.js:113:10)]]></failure>
    </testcase>
    <testcase name="Logging In - Basic Auth cy.request can post" time="0.0000" classname="can post">
      <failure message="`cy.request()` must be provided a fully qualified `url` - one that begins with `http`. By default `cy.request()` will use either the current window&apos;s origin or the `baseUrl` in `cypress.json`. Neither of those values were present.

https://on.cypress.io/request" type="CypressError"><![CDATA[CypressError: `cy.request()` must be provided a fully qualified `url` - one that begins with `http`. By default `cy.request()` will use either the current window's origin or the `baseUrl` in `cypress.json`. Neither of those values were present.

https://on.cypress.io/request
    at Context.request (http://localhost:52036/__cypress/runner/cypress_runner.js:159202:78)
From Your Spec Code:
    at Context.eval (http://localhost:52036/__cypress/tests?p=cypress\integration\code\sampleAuth.js:122:10)]]></failure>
    </testcase>
  </testsuite>
  <testsuite name="cy.visit" timestamp="2022-01-13T06:45:51" tests="1" time="0.2300" failures="1">
    <testcase name="Logging In - Basic Auth cy.visit loads the page using basic auth" time="0.0000" classname="loads the page using basic auth">
      <failure message="`cy.visit()` failed trying to load:

/

We failed looking for this file at the path:

/Users/alvin.flamiano.AWSYS-I/Documents/QA Team KPMG POC Project/Cypress Sample Workspace for Learning/Cypress_demo_AVT_test/Sample_Workspace/

The internal Cypress web server responded with:

  &gt; 404: Not Found" type="CypressError"><![CDATA[CypressError: `cy.visit()` failed trying to load:

/

We failed looking for this file at the path:

/Users/alvin.flamiano.AWSYS-I/Documents/QA Team KPMG POC Project/Cypress Sample Workspace for Learning/Cypress_demo_AVT_test/Sample_Workspace/

The internal Cypress web server responded with:

  > 404: Not Found
    at http://localhost:52036/__cypress/runner/cypress_runner.js:158125:84
    at visitFailedByErr (http://localhost:52036/__cypress/runner/cypress_runner.js:157494:12)
    at http://localhost:52036/__cypress/runner/cypress_runner.js:158105:13
    at tryCatcher (http://localhost:52036/__cypress/runner/cypress_runner.js:13196:23)
    at Promise._settlePromiseFromHandler (http://localhost:52036/__cypress/runner/cypress_runner.js:11131:31)
    at Promise._settlePromise (http://localhost:52036/__cypress/runner/cypress_runner.js:11188:18)
    at Promise._settlePromise0 (http://localhost:52036/__cypress/runner/cypress_runner.js:11233:10)
    at Promise._settlePromises (http://localhost:52036/__cypress/runner/cypress_runner.js:11309:18)
    at _drainQueueStep (http://localhost:52036/__cypress/runner/cypress_runner.js:7903:12)
    at _drainQueue (http://localhost:52036/__cypress/runner/cypress_runner.js:7896:9)
    at Async.../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:52036/__cypress/runner/cypress_runner.js:7912:5)
    at Async.drainQueues (http://localhost:52036/__cypress/runner/cypress_runner.js:7782:14)
From Your Spec Code:
    at Context.eval (http://localhost:52036/__cypress/tests?p=cypress\integration\code\sampleAuth.js:143:10)]]></failure>
    </testcase>
  </testsuite>
</testsuites>